apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: $2a$10$TfDPDXkXsgRmGYIUTGyUB.l0qh3ODA2qUa/ZPRaThoawHkB5/iD32
