apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: flux-system
# secretGenerator:
# - name: cluster-secrets
#   envs:
#   - ../../config.env
resources:
- ./cluster-settings.yaml
- ./cluster-secrets.sops.yaml
