configs:
  cm:
    kustomize.buildOptions: --enable-helm
  cmp:
    create: true
    plugins:
      kustomized-helm:
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build"]
        generate:
          command: [sh, -c]
          args: ["helm template --release-name release-name . > all.yaml && kustomize build"]
