apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-admin
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: dev-secret-store # name of the SecretStore (or kind specified)
  target:
    name: weave-gitops-secret # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: weave-gitops-admin # name of the GCPSM secret key
    remoteRef:
      key: weave-gitops-admin
